# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
